<a href="https://colab.research.google.com/github/xcharita/ineuron/blob/main/Python_Programming_Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Write a Python Program to Add Two Matrices?**


In [1]:
import numpy as np

In [89]:
def add_two_matrices(mtrx1, mtrx2):
  if len(mtrx1) == len(mtrx2):
    return np.add(mtrx1, mtrx2)
  else:
    return "The matrices don't have the same shape"


**Write a Python Program to Multiply Two Matrices?**

In [97]:
def multiply_two_matrices(mtrx1, mtrx2):
  a , b = mtrx1.shape
  c , d = mtrx2.shape
  if a == d and b == c:
    return np.dot(mtrx1, mtrx2)
  else: 
    return "We cannot multiply these two matrices because of dimensionality incongruences"
  

In [66]:
string1 = ''
rows = int(input("How many rows does matrix one have ? "))
columns = int(input("how many columns does matrix one have ? "))

print(rows)

for i in range(columns):
  for j in range(rows):
    n = str(input("Enter the number you would like to add in the array : "))
    string1 = string1  + n + ' ' 
  string1 += ';'


How many rows does matrix one have ? 2
how many columns does matrix one have ? 3
2
Enter the number you would like to add in the array : 5
Enter the number you would like to add in the array : 10
Enter the number you would like to add in the array : 15
Enter the number you would like to add in the array : 20
Enter the number you would like to add in the array : 25
Enter the number you would like to add in the array : 30


In [67]:
matrix1 = string1[:len(string1)-1]

In [69]:
string2 = ''
rows2 = int(input("How many rows does matrix two have ? "))
columns2 = int(input("how many columns does matrix two have ? "))

print(rows2)

for i in range(columns2):
  for j in range(rows2):
    n = str(input("Enter the number you would like to add in the array : "))
    string2 = string2  + n + ' ' 
  string2 += ';'


How many rows does matrix two have ? 3
how many columns does matrix two have ? 2
3
Enter the number you would like to add in the array : 4
Enter the number you would like to add in the array : 8
Enter the number you would like to add in the array : 12
Enter the number you would like to add in the array : 10
Enter the number you would like to add in the array : 14
Enter the number you would like to add in the array : 16


In [70]:
matrix2 = string2[:len(string2)-1]

In [72]:
first_matrix = np.matrix(matrix1)
second_matrix = np.matrix(matrix2)

In [73]:
print(first_matrix)

[[ 5 10]
 [15 20]
 [25 30]]


In [74]:
print(second_matrix)

[[ 4  8 12]
 [10 14 16]]


In [81]:
print(add_two_matrices(first_matrix, second_matrix))

The matrices don't have the same shape


In [98]:
print(multiply_two_matrices(first_matrix, second_matrix))

[[120 180 220]
 [260 400 500]
 [400 620 780]]


**Write a Python Program to Transpose a Matrix?**

In [99]:
transpose_matrix = first_matrix.T

In [100]:
transpose_matrix

matrix([[ 5, 15, 25],
        [10, 20, 30]])

**Write a Python Program to Sort Words in Alphabetic Order?**


In [103]:
def sort_word(wrd):
  return sorted(wrd)

In [104]:
word = str(input("Which word would you like to place in alphabetic order ? "))

Which word would you like to place in alphabetic order ? hallo


In [107]:
print(''.join(sort_word(word)))

ahllo


**Write a Python Program to Remove Punctuation From a String?**

In [101]:
import re

In [110]:
word2 = str(input("From which string would you like to remove the punctuation ? "))

From which string would you like to remove the punctuation ? where are you? which digits can i make from 5.9 ?


In [111]:
print(re.sub(r'[^\w\s]', '', word2))

where are you which digits can i make from 59 
